TAC_AREA_NAME: CA ISO-TAC
execution_type: null
forecast_type: SLD_FCST
market_run_id: DAM
training_set_end: 2024-01-20
training_set_start: 2024-01-01
validation_set_end: 2024-01-30
validation_set_start: 2024-01-21
zone_id: NP15
